### ISSUE TITLE
First issue

### ISSUE THREAD

**Issue by sushanthakumar** [sushanthakumar/git-handson#1]
Description: issue 1
Suggestion (if any) : Try option1

Task List Here
- [ ] [Design Task](https://github.com/sushanthakumar/git-handson/issues/2)
- [x] [Implementation](https://github.com/sushanthakumar/git-handson/issues/3)

**Comment by sushanthakumar** [comment]
Add Task List Here
- [ ] [eerrtt](https://github.com/sushanthakumar/git-handson/issues/3)

**Comment by shafnamol** [comment]
issue fixed
